version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "80:80"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: on-failure
    ports:
      - "6333:6333"
      - "6334:6334"
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    depends_on:
      - backend
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
volumes:
  postgres_data:
  production_traefik:
