version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "80:80"
    networks:
      - default
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  qdrant:
    image: qdrant/qdrant:latest
    restart: on-failure
    expose:
      - 6334
      - 6333
    networks:
      - default
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    depends_on:
      - backend
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    networks:
      - default
volumes:
  postgres_data:
  production_traefik:

networks:
  default:
